plugins {
    id 'com.android.application'
}

def targetAbi = project.findProperty('targetAbi') ?: 'arm64-v8a'

android {
    namespace 'com.jieshuo.offlinetranslator'
    compileSdk 35

    defaultConfig {
        applicationId 'com.jieshuo.offlinetranslator'
        minSdk 28
        targetSdk 35
        versionCode 4
        versionName '0.4.0-test'

        ndk {
            abiFilters targetAbi
        }

        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    androidResources {
        noCompress += ['bin', 'spm']
    }

    packaging {
        jniLibs {
            useLegacyPackaging = true
        }
    }
}

dependencies {
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test:runner:1.6.2'
    androidTestImplementation 'androidx.test:core:1.6.1'
}
