plugins {
    id 'com.android.application'
}

android {
    namespace 'com.jieshuo.offlinetranslator'
    compileSdk 35

    defaultConfig {
        applicationId 'com.jieshuo.offlinetranslator'
        minSdk 28
        targetSdk 35
        versionCode 3
        versionName '0.3.0-test'

        ndk {
            abiFilters 'arm64-v8a'
        }
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    androidResources {
        noCompress += ['bin', 'spm']
    }

    packaging {
        jniLibs {
            useLegacyPackaging = true
        }
    }
}
